/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

/**
 *
 * @author perpustakaan
 */
public class DlgAbout extends javax.swing.JDialog {

    
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel6 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        BtnKeluar = new widget.Button();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        jLabel31 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ About Program ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 50, 50));
        jLabel6.setText(".: Aplikasi ");
        jLabel6.setName("jLabel6"); // NOI18N
        internalFrame1.add(jLabel6);
        jLabel6.setBounds(10, 18, 90, 20);

        panelGlass1.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass1.setOpaqueImage(false);
        panelGlass1.setRound(false);
        panelGlass1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(50, 50, 50));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Versi Custom :");
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass1.add(jLabel7);
        jLabel7.setBounds(0, 8, 104, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(50, 50, 50));
        jLabel17.setText("Update 2024-08-19");
        jLabel17.setName("jLabel17"); // NOI18N
        panelGlass1.add(jLabel17);
        jLabel17.setBounds(107, 8, 120, 14);

        internalFrame1.add(panelGlass1);
        panelGlass1.setBounds(10, 150, 450, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(50, 50, 50));
        jLabel16.setText(".: Custom ");
        jLabel16.setName("jLabel16"); // NOI18N
        internalFrame1.add(jLabel16);
        jLabel16.setBounds(10, 130, 110, 20);

        panelGlass4.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass4.setOpaqueImage(false);
        panelGlass4.setRound(false);
        panelGlass4.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(50, 50, 50));
        jLabel19.setText("RS Permata Medika Kebumen, RS Handayani Lampung Utara, ");
        jLabel19.setName("jLabel19"); // NOI18N
        panelGlass4.add(jLabel19);
        jLabel19.setBounds(126, 160, 320, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(50, 50, 50));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Blog :");
        jLabel24.setName("jLabel24"); // NOI18N
        panelGlass4.add(jLabel24);
        jLabel24.setBounds(0, 30, 55, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(50, 50, 50));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Phone :");
        jLabel20.setName("jLabel20"); // NOI18N
        panelGlass4.add(jLabel20);
        jLabel20.setBounds(0, 10, 55, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(50, 50, 50));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Email :");
        jLabel21.setName("jLabel21"); // NOI18N
        panelGlass4.add(jLabel21);
        jLabel21.setBounds(0, 50, 55, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(50, 50, 50));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Github :");
        jLabel22.setName("jLabel22"); // NOI18N
        panelGlass4.add(jLabel22);
        jLabel22.setBounds(0, 70, 55, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(50, 50, 50));
        jLabel23.setText("Kontributor & Donatur : RS Jeumpa Pontianak Kalimantan Barat, RS Sadewa Yogyakarta,");
        jLabel23.setName("jLabel23"); // NOI18N
        panelGlass4.add(jLabel23);
        jLabel23.setBounds(10, 100, 440, 14);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(50, 50, 50));
        jLabel25.setText("RS Puri Husada Sleman Yogyakarta, RS Pelita Insani Martapura,");
        jLabel25.setName("jLabel25"); // NOI18N
        panelGlass4.add(jLabel25);
        jLabel25.setBounds(126, 120, 320, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(50, 50, 50));
        jLabel26.setText("RS Assyifa Manna, RS Arvita Bunda Sleman Yogyakarta,");
        jLabel26.setName("jLabel26"); // NOI18N
        panelGlass4.add(jLabel26);
        jLabel26.setBounds(126, 140, 320, 14);

        panelGlass5.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass5.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass5.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass5.setRound(false);
        panelGlass5.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass5.setLayout(null);
        panelGlass4.add(panelGlass5);
        panelGlass5.setBounds(0, 260, 330, 70);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass4.add(BtnKeluar);
        BtnKeluar.setBounds(340, 290, 100, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(50, 50, 50));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Bagi yang ingin melakukan Donasi, bisa ke Rekening BSI 1015369872, kode bank 451");
        jLabel27.setName("jLabel27"); // NOI18N
        panelGlass4.add(jLabel27);
        jLabel27.setBounds(16, 220, 420, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(50, 50, 50));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("atas nama Windiarto");
        jLabel28.setName("jLabel28"); // NOI18N
        panelGlass4.add(jLabel28);
        jLabel28.setBounds(16, 240, 420, 14);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(50, 50, 50));
        jLabel32.setText("elkhanza.wordpress.com, simrskhanza.weebly.com, yaski.or.id");
        jLabel32.setName("jLabel32"); // NOI18N
        panelGlass4.add(jLabel32);
        jLabel32.setBounds(58, 30, 430, 14);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(50, 50, 50));
        jLabel33.setText("khanza_media@yahoo.com, khanzasoftmedia@gmail.com");
        jLabel33.setName("jLabel33"); // NOI18N
        panelGlass4.add(jLabel33);
        jLabel33.setBounds(58, 50, 420, 14);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(50, 50, 50));
        jLabel34.setText("github.com/mas-elkhanza     Instagram : simrskhanza");
        jLabel34.setName("jLabel34"); // NOI18N
        panelGlass4.add(jLabel34);
        jLabel34.setBounds(58, 70, 420, 14);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(50, 50, 50));
        jLabel35.setText("RS Haji Kamino Way Kanan, RS PKU Jatinom Klaten, dll");
        jLabel35.setName("jLabel35"); // NOI18N
        panelGlass4.add(jLabel35);
        jLabel35.setBounds(126, 180, 320, 14);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(50, 50, 50));
        jLabel36.setText("08562675039     Pengembang : Windiarto Nugroho, Dewi Ekawati, YASKI dll");
        jLabel36.setName("jLabel36"); // NOI18N
        panelGlass4.add(jLabel36);
        jLabel36.setBounds(58, 10, 420, 14);

        internalFrame1.add(panelGlass4);
        panelGlass4.setBounds(10, 200, 454, 370);

        jLabel37.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 50, 50));
        jLabel37.setText(".: Developer");
        jLabel37.setName("jLabel37"); // NOI18N
        internalFrame1.add(jLabel37);
        jLabel37.setBounds(10, 180, 110, 20);

        panelGlass2.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass2.setOpaqueImage(false);
        panelGlass2.setRound(false);
        panelGlass2.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(50, 50, 50));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Database Server :");
        jLabel31.setName("jLabel31"); // NOI18N
        panelGlass2.add(jLabel31);
        jLabel31.setBounds(0, 22, 104, 14);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(50, 50, 50));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Versi Aplikasi :");
        jLabel38.setName("jLabel38"); // NOI18N
        panelGlass2.add(jLabel38);
        jLabel38.setBounds(0, 8, 104, 14);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(50, 50, 50));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Default Database :");
        jLabel39.setName("jLabel39"); // NOI18N
        panelGlass2.add(jLabel39);
        jLabel39.setBounds(0, 36, 104, 14);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(50, 50, 50));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("File Konfigurasi :");
        jLabel40.setName("jLabel40"); // NOI18N
        panelGlass2.add(jLabel40);
        jLabel40.setBounds(0, 50, 104, 14);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(50, 50, 50));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Default Port :");
        jLabel41.setName("jLabel41"); // NOI18N
        panelGlass2.add(jLabel41);
        jLabel41.setBounds(0, 64, 104, 14);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(50, 50, 50));
        jLabel42.setText("Untuk mensetting aplikasi menjadi Client");
        jLabel42.setName("jLabel42"); // NOI18N
        panelGlass2.add(jLabel42);
        jLabel42.setBounds(230, 8, 210, 14);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(50, 50, 50));
        jLabel43.setText("Server, ganti HOST Localhost dengan");
        jLabel43.setName("jLabel43"); // NOI18N
        panelGlass2.add(jLabel43);
        jLabel43.setBounds(230, 22, 200, 14);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(50, 50, 50));
        jLabel44.setText("alamat/IP Address dari server yang di");
        jLabel44.setName("jLabel44"); // NOI18N
        panelGlass2.add(jLabel44);
        jLabel44.setBounds(230, 36, 200, 14);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(50, 50, 50));
        jLabel45.setText("gunakan. Jagan lupa untuk mengatur hak");
        jLabel45.setName("jLabel45"); // NOI18N
        panelGlass2.add(jLabel45);
        jLabel45.setBounds(230, 50, 220, 14);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(50, 50, 50));
        jLabel46.setText("akses di MySQL server agar terkoneksi");
        jLabel46.setName("jLabel46"); // NOI18N
        panelGlass2.add(jLabel46);
        jLabel46.setBounds(230, 64, 210, 14);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(50, 50, 50));
        jLabel47.setText("Update 2023-09-12");
        jLabel47.setName("jLabel47"); // NOI18N
        panelGlass2.add(jLabel47);
        jLabel47.setBounds(107, 8, 120, 14);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(50, 50, 50));
        jLabel48.setText("MySQL Server");
        jLabel48.setName("jLabel48"); // NOI18N
        panelGlass2.add(jLabel48);
        jLabel48.setBounds(107, 22, 120, 14);

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(50, 50, 50));
        jLabel49.setText("sik");
        jLabel49.setName("jLabel49"); // NOI18N
        panelGlass2.add(jLabel49);
        jLabel49.setBounds(107, 36, 120, 14);

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(50, 50, 50));
        jLabel50.setText("database.xml");
        jLabel50.setName("jLabel50"); // NOI18N
        panelGlass2.add(jLabel50);
        jLabel50.setBounds(107, 50, 120, 14);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(50, 50, 50));
        jLabel51.setText("3306");
        jLabel51.setName("jLabel51"); // NOI18N
        panelGlass2.add(jLabel51);
        jLabel51.setBounds(107, 64, 120, 14);

        internalFrame1.add(panelGlass2);
        panelGlass2.setBounds(7, 38, 454, 90);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    // End of variables declaration//GEN-END:variables

}
